Cast2023/cast

documentation/cast_db-architecture.md, documentation/cast_db.vuerd.json
#85 Maija and me have updated the db picture based on discussions yesterday.
=> Update database structure to reflect latest proposed changes

frontend/src/Components/AppRoutes.js, frontend/src/Components/Logout.js
This is merely meant to make development easier for this sprint. Not meant as a permanent finished feature. Clears local storage and Navigates to route "/". No tests written for this.
=> Initial logout feature. Untested

frontend/src/Components/AppRoutes.js, frontend/src/Components/Profile.js, frontend/src/Components/Search.js
An initial routing for profile-id's. Works both for user and search results. 
TODO: tests, disable edit from search results. Refactor code. Made some delicious spaghetti.
=> Initial routing for profile-ids

frontend/src/Components/Roboroute.js, frontend/src/Components/Search.js, tests/robottest/container.robot, tests/robottest/local-dev.robot, tests/robottest/search_view.robot
A few tests for the Search view. Please let me know if these need more work.
=> Improve robot tests

documentation/cast_db-architecture.md, documentation/cast_db.vuerd.json
The database architectural picture in the documentation has been modified to reflect the updates in the db model.
=> Update db arch doc

backend/restapi/models.py, backend/restapi/views.py, documentation/rest_api.md
Add two filters for certificate valid until (gte, lte). 
Update documentation
This pull request should perhaps be accepted after Jiisala accepts the previous pull request (#236 )
=> Cert date filter

backend/restapi/serializers.py, backend/restapi/urls.py, backend/restapi/views.py, frontend/src/Components/SkillsCard.js, frontend/src/Reducers/skillCardReducer.js, frontend/src/Reducers/store.js, frontend/src/Services/techService.js, tests/robottest/profile_tech_skills.robot
Skill card now more user friendly. One failing robot test commented out. Will get fixed ASAP. 
Not a finished feature yet, but getting there.
=> Add skills refactored

backend/restapi/serializers.py
An initial version for expanding api/consultant/<id:pk> to support updating certificates and projects. 
**Features that should work:**
- An existing certificate valid_until can be updated
- A new certificate existing in database can be added to employee
- Following fields in an existing project can be updated: employee_participation_start_date, employee_participation_end_date, alloaction_busy
- A new project already in db can be added to employee with above mentioned fields. Fields are left empty as default if no information is given. 
**Known issues:**
- Tests are missing. Will be added this week after refactored tests from last week are merged into development. 
- Validation rests on Django DRF's features. Error messages are not very descriptive (e.g. invalid pk).
=> Add partial update for certs and projects. Initial version

backend/restapi/models.py
Change constaint on variable project_name.
=> Change project_name constaint to unique=True

frontend/src/Reducers/projectCardReducer.js, frontend/src/Reducers/store.js, frontend/src/Services/projectService.js
- created slice for project and initial reducers
- created service for projects
- projects can now be initialized from API. Initialization TBA. 
**Known issues**
- missing tests. More reasonable to create tests when functionality more expanded.
=> Project slice and service

backend/restapi/tests/test_api_cert_route.py, backend/restapi/tests/test_api_consultant.py, backend/restapi/tests/test_api_filter_consultant.py, backend/restapi/tests/test_api_project_route.py, backend/restapi/tests/test_api_tech_route.py, backend/restapi/tests/test_google_api.py, backend/restapi/urls.py, backend/restapi/views.py
This pull request includes:
- Refactoring in API tests file structure
- New tests for API, including certs, projects, filtering & expanded consultant
Tests will need further expansion as the API functionalities keep progressing.
=> Api unittests

frontend/src/Components/CertsCard.js
Add certificates into cert card, closes #208
=> View certs

frontend/src/Components/ProjectsCard.js
Similar plus-symbol added to project card as available in skills-card.
=> Add project - symbol added

frontend/src/Components/ProjectsCard.js, frontend/src/Reducers/projectCardReducer.js, frontend/src/Services/consultantService.js
What's new:
- when user presses submit button, data is sent to backend via a PATCH-request. 
What is still missing:
- Data validation needs improvements (perhaps new user story)
- User should be shown a verification of submission status
- Should state be cleared when data is submitted? 
- Robotests are missing. 
Known issues:
- Employee can only be assigned to a project once. Should employee be able to take part in a project multiple times?
=> Project card patch info

frontend/src/Components/ProjectsCard.js
A quick bug fix. 
**Bug description:** After submitting a new project pressing plus-symbol caused a crash. 
Known issues:
- fix is not optimal in efficiency. Needs refactoring in next sprint when add-feature is developed further.
=> Quick bug fix

backend/restapi/serializers.py
Refactor and improve updating skills. Skills now updated using Django-features (instances). Less code, more unified functionality.
=> Bug fix django skills update

documentation/rest_api.md
Document new feature to be built in REST API.  As this pull request is about documentation, the request in itself is hopefully self explanatory. 
Related task: #330
Related user story: #321
=> Update API documentation

frontend/src/Components/Search.js, frontend/src/Reducers/consultantReducer.js
User story #13 
Search page: consultants can be filtered by certification
=> Filter cert

frontend/package-lock.json, frontend/package.json, frontend/src/Components/ProjectsCard.js
Calendar view now shows weeks from Mon-Sun. New package installed (moment). DayJs still in use. Need to be refactored out from code. Then we can uninstall DayJs.
=> Datepicker week start

frontend/src/Components/ProjectsCard.js, robot/tests/profile/projects.robot
Project card layout for reviewing projects harmonized with the layout of other cards, and robot tests for reviewing projects added.
Note:  Adding a new project does not function; a list of projects is not generated. I did not do changes to that part of the code and cannot figure out why that is. If I add <div> element to Table, adding projects works, but the layout is not as wanted then. That needs to be checked.
=> Projectscard in table format + robot tests

frontend/src/Components/CertsCard.js, robot/tests/profile/certs.robot
The three added tests pass locally.
=> Added robot tests for cert review

frontend/src/Components/Api.js, robot/tests/api_view.robot
Fixed two unstable robot tests
=> Fix api robot

backend/.coveragerc, backend/restapi/serializers.py, backend/restapi/tests/test_api_filter_consultant.py, backend/restapi/urls.py, backend/restapi/views.py, backend/tasks.py, documentation/rest_api.md, documentation/testing-details-and-instructions.md
- Added couple of new unittests
- Removed unneeded imports from views.py
- Removed Import-Certificate feature from backend
- Backend unittests pass
- all Robot tests pass
=> Backend unittests

frontend/src/Components/Search.js
- Filters horizontally on same height (row)
- Consultant cards refined. Fields removed, certificates grouped by vendor (+count) added.
=> Searchpage UI

frontend/src/Reducers/certCardReducer.test.js, frontend/src/Reducers/integrationReducer.test.js, frontend/src/Reducers/projectCardReducer.test.js
=> Reducer tests
